api:
  twelvedata:
    key: 1bbad15ba5d5406585b9f628972dfcdc
spring:
  flyway:
    baseline-on-migrate: true
    locations: db.migrations
    url: jdbc:mysql://localhost:3306/TransactionServicePrototype?createDatabaseIfNotExist=true
    user: root
    password: root
  application:
    name: TransactionServicePrototype
  datasource:
    url: jdbc:mysql://localhost:3306/TransactionServicePrototype?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html